### ISSUE TITLE
Entrega Trabajo Práctico N°1

### ISSUE THREAD

**Issue by FacaHerrera** [FacaHerrera/2020_K2002_Grupo_6#1]
Solicito correcion del Trabajo Practico : @santiagoferreiros

**Comment by santiagoferreiros** [comment]
@FacaHerrera @lucasmaksymon @agusfila @IgnacioGomezL 

Excelente trabajo. 
Un detalle importante, la función guardar se invoca para cada caracter leído y en cada invocación vuelve abrir el archivo mediante fopen. Eso es muy poco eficiente. Generalmente los archivos deben abrir una única vez y no cada vez que se desea escribir.

Les repito, única observación ! El resto exclente
Nota: 9

Felicitaciones y a seguir así ! =)
